### ISSUE TITLE
Potential memory leak for decoded frames in python

### ISSUE THREAD

**Issue by njlxyaoxinwei** [scanner-research/hwang#11]
Frameserver quickly fills up RAM when working with movie data, so I dug around and found this. Looks like `buffer` is never freed at https://github.com/scanner-research/hwang/blob/master/hwang/hwang_python.cpp#L88

https://github.com/pybind/pybind11/issues/279 seems to suggest that pybind11 copies those bytes in `buffer` anyways.

This may be related to https://github.com/scanner-research/hwang/issues/2

**Comment by willcrichton** [comment]
Fixed in #39d42cc69f1dedc32ab2891264fa7c3db5ca07df
