### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sola777** [scanner-research/hwang#2]
Hi Alex,

I also met another problem which might be memory leak. When I run 32 processes to retrieve frames, my memory kept increasing all the time, fullfill my 240G memory after about 30 mins. 
A simple test case is like this:
```
storage = StorageBackend.make_from_config(StorageConfig.make_gcs_config('esper'))
for i in range(100000): 
    video_path = 'tvnews/videos/CNNW_20150219_200000_CNN_Newsroom_With_Brooke_Baldwin.mp4'
    video_file = RandomReadFile(storage, video_path.encode('ascii'))
    video = Decoder(video_file)
    img_list = video.retrieve(range(0, 100000, 100))
    print i
```
After about 40 iterations, my memory usage increases about 1.7G. I am not sure if I need to explictly release memory? Thank you!

**Comment by apoms** [comment]
Hey! Sorry, for not getting back to you on this. Was the issue resolved?

**Comment by sola777** [comment]
Yes, I find this issue might come from python itself rather than the library, so I closed it.
